# Generated by Django 5.1.4 on 2026-03-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KpiDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('area', models.CharField(choices=[('Outcomes', 'Outcomes'), ('Outputs', 'Outputs'), ('Service Delivery', 'Service Delivery'), ('Management', 'Management'), ('Cross-Cutting', 'Cross-Cutting')], max_length=50)),
                ('unit', models.CharField(max_length=20)),
                ('target', models.FloatField()),
                ('weight', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'pms_kpi_definitions',
                'ordering': ['area', 'name'],
            },
        ),
    ]
