# Generated by Django 5.1.4 on 2026-03-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpidefinition',
            name='allowable_variance',
            field=models.FloatField(default=5.0, help_text='Acceptable variance % (e.g. 5 means ±5%)'),
        ),
        migrations.AddField(
            model_name='kpidefinition',
            name='prev_year_performance',
            field=models.FloatField(blank=True, help_text="Last year's baseline performance", null=True),
        ),
        migrations.AlterField(
            model_name='kpidefinition',
            name='target',
            field=models.FloatField(help_text='Annual year target'),
        ),
    ]
