# Generated by Django 5.1.4 on 2026-03-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('me', 'M&E Consultant'), ('admin', 'System Administrator'), ('entity', 'Entity User')], default='me', max_length=20),
        ),
    ]
