# Generated by Django 5.1.4 on 2026-03-03 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=2)),
                ('period', models.CharField(max_length=20)),
                ('submitted_by', models.CharField(max_length=150)),
                ('submitted_date', models.DateField(auto_now_add=True)),
                ('kpi_count', models.PositiveIntegerField(default=0)),
                ('overall_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('reviewed_by', models.CharField(blank=True, max_length=150)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('ceo_comment', models.TextField(blank=True)),
                ('overall_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='entities.entity')),
            ],
            options={
                'db_table': 'pms_submissions',
                'ordering': ['-submitted_date'],
            },
        ),
        migrations.CreateModel(
            name='SectionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('score', models.FloatField()),
                ('weight', models.PositiveIntegerField()),
                ('weighted', models.FloatField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='submissions.submission')),
            ],
            options={
                'db_table': 'pms_section_scores',
            },
        ),
        migrations.CreateModel(
            name='KpiActual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=20)),
                ('target', models.FloatField()),
                ('actual', models.FloatField()),
                ('variance', models.FloatField()),
                ('raw_score', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('weighted', models.FloatField()),
                ('comment', models.TextField(blank=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='submissions.submission')),
            ],
            options={
                'db_table': 'pms_kpi_actuals',
            },
        ),
    ]
