# Generated by Django 5.1.4 on 2026-03-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpiactual',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='kpiactual',
            name='target',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='ceo_comment',
        ),
        migrations.AddField(
            model_name='kpiactual',
            name='agreed_rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kpiactual',
            name='allowable_variance',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='kpiactual',
            name='consultant_rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kpiactual',
            name='evaluatee_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kpiactual',
            name='period_target',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='kpiactual',
            name='prev_year_performance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kpiactual',
            name='recommendation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kpiactual',
            name='self_rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kpiactual',
            name='year_target',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='submission',
            name='reviewer_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='kpiactual',
            name='raw_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kpiactual',
            name='weighted',
            field=models.FloatField(default=0.0),
        ),
    ]
