# Generated by Django 5.1.4 on 2026-03-03 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Pending Signature', 'Pending Signature'), ('Expired', 'Expired')], default='Active', max_length=30)),
                ('total_kpis', models.PositiveIntegerField(default=0)),
                ('reviewer', models.CharField(blank=True, max_length=150)),
                ('signed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='entities.entity')),
            ],
            options={
                'db_table': 'pms_contracts',
                'ordering': ['-created_at'],
                'unique_together': {('entity', 'period')},
            },
        ),
    ]
